# Generated by Django 3.2.7 on 2021-09-02 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quality', '0003_auto_20210902_0517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='owner',
            new_name='user',
        ),
    ]
